### ISSUE TITLE
Make `@code-pushup/eslint-config/angular-ngrx` compatible with `@ngrx/eslint-plugin` v18

### ISSUE THREAD

**Issue by getlarge** [code-pushup/eslint-config#22]
### User story

The `recommended-requiring-type-checking` config was removed in `@ngrx/eslint-plugin` 18.

![Image](https://github.com/user-attachments/assets/1eca8440-fc92-4d34-a97f-c9aeff40d6ba)

An option could be to add [the rules](https://github.com/ngrx/platform/blob/17.2.0/modules/eslint-plugin/src/configs/recommended-requiring-type-checking.ts) that were part of this configuration manually.

---

See this [related issue](https://github.com/ngrx/platform/issues/3658)

---

I will open a PR.

### Acceptance criteria

You tell me :) 

### Minimal reproduction of current behaviour

Use the `@code-pushup/eslint-config` in a workpsace using  `@ngrx/*` >= 18.

### Which configuration is this related to?

NgRx

### ESLint version

8.57.0

**Comment by matejchalk** [comment]
@getlarge Thanks for taking care of this 🙂  I've just released your fix (version [`0.9.1`](https://github.com/code-pushup/eslint-config/releases/tag/0.9.1)) 🚀
